name: cppcheck

on:
  push:
    branches: [ main, develop, ci ]
  pull_request:
    branches: [ main, develop, ci ]

env:
  CPPCHECK_VERSION: 2.9

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install cppcheck
      shell: bash
      run: |
          cd /tmp/
          wget https://github.com/danmar/cppcheck/archive/$CPPCHECK_VERSION.tar.gz
          tar xfz $CPPCHECK_VERSION.tar.gz
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ../cppcheck-$CPPCHECK_VERSION/
          make -j $(nproc)
          sudo make install

    - name: Run cppcheck
      shell: bash
      run: |
          cppcheck \
            --std=c++20 \
            --suppress=useStlAlgorithm \
            --inline-suppr \
            --enable=all \
            --template='[{file}:{line}]:({severity}),[{id}],{message}' \
            --force -q -j $(nproc) \
            -i embedded/ \
            ./ 2>&1 | tee cppcheck.txt

    - name: Parse and colorize cppcheck
      shell: bash
      run: python ./ci/colorize_cppcheck_results.py

    - name: Upload cppcheck results as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
          name: OpenStudioLabs-${{ github.sha }}-cppcheck_results.txt
          path: cppcheck.txt
